service: projeto01-AWS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iam:
      role:
          statements:
           - Effect: Allow
             Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
              - dynamodb:scan
             Resource:
              - arn:aws:dynamodb:sa-east-1:026539412501:table/ItemTableNew

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetcheItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: src/fetcheItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /item/{id}
          method: put

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
